networks:
  main:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -backend
      -frontend
    networks:
      - main
  backend:
    build:
      context: ./backend
    networks:
      - main
  frontend:
    build:
      context: ./frontend
    networks:
      - main